# Generated by Django 5.1 on 2026-05-16 14:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Portefeuille',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_jours_impayes', models.PositiveIntegerField(default=0)),
                ('montant_journalier', models.DecimalField(decimal_places=2, max_digits=12)),
                ('periodes_paiement', models.JSONField(default=list)),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('CONFIRME_RH', 'Confirmé RH'), ('PAYE', 'Payé'), ('IMPAYE', 'Impayé')], default='EN_ATTENTE', max_length=15)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('modifie_le', models.DateTimeField(auto_now=True)),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='portefeuilles', to='employes.employe')),
            ],
            options={
                'db_table': 'portefeuilles',
                'ordering': ['-cree_le'],
            },
        ),
        migrations.CreateModel(
            name='HistoriquePaiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_paiement', models.DateField()),
                ('montant_total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('nombre_jours', models.PositiveIntegerField()),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='historique_paiements', to='employes.employe')),
                ('portefeuille', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='portefeuilles.portefeuille')),
            ],
            options={
                'db_table': 'historique_paiements',
                'ordering': ['-date_paiement'],
            },
        ),
    ]
