# Generated by Django 6.0.5 on 2026-05-23 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portefeuilles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historiquepaiement',
            name='periodes_paiement',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='historiquepaiement',
            name='statut',
            field=models.CharField(blank=True, choices=[('EN_ATTENTE', 'En attente'), ('PAYE', 'Payé'), ('IMPAYE', 'Impayé')], max_length=15, null=True),
        ),
    ]
