const u = {
    'message_follower_ids': [997, 982, 1003],
    'address_id': [1, 'IVOIREORGANICS'],
    'attendance_access': False,
    'is_syndicated': False,
    'coach_id': False,
    'resource_id': [59, ' DJE YAO Ulrich Fiacre Thibaut '],
    'color': 0,
    'country_id': False,
    'image': False,
    'slip_ids': [79, 88, 127, 129, 203],
    'write_uid': [79, 'Sylvie MONKAM'],
    'payslip_count': 5, 'manager': False,
    'message_unread': False,
    'gender': 'male',
    'image_small': False,
    'create_date': '2022-11-26 11:31:16',
    'identification_id': 'CI004770423',
    'children': 0,
    'message_summary': ' ',
    'code': False,
    'city': False,
    'time_efficiency': 1.0,
    'total_wage': 9000.0,
    'display_name': ' DJE YAO Ulrich Fiacre Thibaut ',
    'contract_id': [150, 'DJE YAO Ulrich Fiacre Thibaut Thibaut'],
    'message_is_follower': False,
    '__last_update': '2024-03-07 08:58:06',
    'work_phone': '05 06 19 92 52',
    'current_leave_id': False,
    'message_last_post': False,
    'journal_id': [3, 'Timesheet Journal'],
    'medic_exam': False, 'id': 59,
    'parent_id': [10, 'Alice NOUTCHEUWA KAMGA'],
    'state': 'absent',
    'last_login': False,
    'category_ids': [],
    'contracts_count': 3,
    'vehicle': False,
    'current_leave_state': False,
    'active': True,
    'department_id': [12, 'Conditionnement'],
    'company_id': [1, 'IVOIREORGANICS'],
    'otherid': False,
    'mobile_phone': '05 06 19 92 52',
    'name': ' DJE YAO Ulrich Fiacre Thibaut ',
    'create_uid': [70, 'Stephane NDJEUTCHOU']
    , 'bank_account_id': False,
    'child_ids': [],
    'user_id': False,
    'resource_type': 'user',
    'birthday': '2002-11-14',
    'leave_date_to': False,
    'write_date': '2024-03-07 08:58:06', ' is_expat': False,
                                            'sinid': False, 'calendar_id': False,
    'marital': 'single', 'work_email': False,
    'remaining_leaves': 0.0, 'job_id': [22, 'Journalier'],
    'work_location': False, 'image_medium': False,
    'leaves_count': 0, 'product_id': [1, 'Service'],
    'uom_id': [5, 'Hour(s)'], 'name_related': ' DJE YAO Ulrich Fiacre Thibaut ',
    'ssnid': False, 'leave_date_from': False,
    'last_sign': '2026-06-25 14:39:59'
    , 'passport_id': False, 'address_home_id': [1062, 'Larabia'],
    'contract_ids': [66, 148, 150],
    'place_of_birth': 'Bonoua', 'message_ids': [1550],
    'login': False, 'timesheet_count': 0,
    'notes': False, 'vehicle_distance': 0
}