# Generated by Django 5.1 on 2026-06-30 13:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('odoo_attendance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoriquePaiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_paiement', models.DateField()),
                ('montant_total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('nombre_jours', models.PositiveIntegerField()),
                ('periodes_paiement', models.JSONField(default=list)),
                ('statut', models.CharField(blank=True, choices=[('EN_ATTENTE', 'En attente'), ('PAYE', 'Payé'), ('IMPAYE', 'Impayé')], max_length=15, null=True)),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='historique_paiements', to='odoo_attendance.employe')),
            ],
            options={
                'db_table': 'historique_paiements',
                'ordering': ['-date_paiement'],
            },
        ),
    ]
