# Generated by Django 5.1 on 2026-08-07 19:01

import django.db.models.deletion
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('odoo_attendance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigurationPaiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('MANUEL', 'Manuel'), ('AUTOMATIQUE', 'Automatique')], default='MANUEL', max_length=15)),
                ('date_changement_mode', models.DateTimeField(blank=True, null=True)),
                ('derniere_execution_auto', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'configuration_paiement',
            },
        ),
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_paiement', models.DateField()),
                ('statut', models.CharField(choices=[('PENDING', 'En attente'), ('ENCOURS', 'En cours'), ('SUCCESS', 'Payé'), ('FAILED', 'Echoué')], default='PENDING', max_length=15)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=12)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('methode_paiement', models.CharField(choices=[('ORANGE_CIV', 'Orange Money'), ('MTN_MOMO_CIV', 'MTN Money')], max_length=15)),
                ('type_paiement', models.CharField(choices=[('GROUPE', 'Paiement groupé'), ('AUTOMATIQUE', 'Paiement automatique'), ('DEMANDE', 'Paiement à la demande')], default='DEMANDE', max_length=15)),
                ('reference', models.CharField(editable=False, max_length=100, unique=True)),
                ('reponse_brute', models.JSONField(blank=True, null=True)),
                ('date_envoi', models.DateTimeField(blank=True, null=True)),
                ('date_confirmation', models.DateTimeField(blank=True, null=True)),
                ('attendances', models.ManyToManyField(related_name='paiements', to='odoo_attendance.attendance')),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='historique_paiements', to='odoo_attendance.employe')),
            ],
            options={
                'db_table': 'paiements',
                'ordering': ['-date_paiement'],
            },
        ),
    ]
