# Generated by Django 5.1 on 2026-08-09 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paiements', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paiement',
            name='statut',
            field=models.CharField(choices=[('ENCOURS', 'En cours'), ('SUCCESS', 'Payé'), ('FAILED', 'Echoué')], default='ENCOURS', max_length=15),
        ),
    ]
