# Generated by Django 5.1 on 2026-08-10 12:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_load_initial_sites'),
        ('paiements', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configurationpaiement',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='configuration_paiement', to='accounts.site'),
        ),
    ]
