# Generated by Django 5.1 on 2026-07-20 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paiements', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paiement',
            name='bulk_transfer_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
