# Generated by Django 5.1 on 2026-07-30 09:52

import django.db.models.deletion
import phonenumber_field.modelfields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('odoo_id', models.CharField(max_length=20, unique=True)),
                ('nom_complet', models.CharField(max_length=150)),
                ('departement', models.CharField(max_length=100)),
                ('site_travail', models.CharField(max_length=100)),
                ('statut', models.CharField(choices=[('ACTIF', 'Actif'), ('INACTIF', 'Inactif')], default='INACTIF', max_length=10)),
                ('mobile_phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None)),
                ('operateur_mobile', models.CharField(blank=True, choices=[('ci.orange', 'Orange Money'), ('ci.mtn', 'MTN Money')], max_length=10, null=True)),
                ('notchpay_beneficiary_id', models.CharField(blank=True, max_length=50, null=True, unique=True)),
            ],
            options={
                'db_table': 'employes',
            },
        ),
        migrations.CreateModel(
            name='TarifJournalier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, default=3000.0, max_digits=12)),
                ('date_effet', models.DateField(unique=True)),
            ],
            options={
                'verbose_name': 'Tarif Journalier',
                'verbose_name_plural': 'Tarif Journaliers',
                'db_table': 'tarif_journaliers',
                'ordering': ['-date_effet'],
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('sign_in', 'Entrée'), ('sign_out', 'Sortie')], default='sign_out', max_length=10)),
                ('date_work', models.DateTimeField()),
                ('date', models.DateField(editable=False)),
                ('worked_hours', models.FloatField(blank=True, null=True)),
                ('odoo_attendance_id', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('date_validation_paiement', models.DateTimeField(blank=True, null=True)),
                ('statut_paiement', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('PAYE', 'Payé'), ('IMPAYE', 'Impayé'), ('EN_COURS', 'En cours'), ('EN_COURS_TRAITEMENT_SUPPRESION', 'En cours de traitement (signalement SUPPRESION)'), ('EN_COURS_TRAITEMENT_CREATION', 'En cours de traitement (signalement CREATION)'), ('ARCHIVE', "Supprimé par l'admin")], default='EN_ATTENTE', max_length=50)),
                ('statut_attendance', models.CharField(choices=[('CREATION_AUTO', 'Créé par le système'), ('CREATION_MANUELLE', "Créé par l'admin")], default='CREATION_AUTO', max_length=20)),
                ('montant_journalier', models.DecimalField(decimal_places=2, max_digits=12)),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='odoo_attendance.employe')),
            ],
            options={
                'db_table': 'odoo_attendance',
            },
        ),
        migrations.CreateModel(
            name='Signalement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_demande', models.CharField(choices=[('CREATION', 'Demande de création de présence'), ('SUPPRESSION', 'Demande de suppression de présence')], max_length=15)),
                ('jour', models.DateField()),
                ('raison', models.TextField()),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('attendance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='signalements', to='odoo_attendance.attendance')),
                ('demandeur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='signalements_envoyes', to=settings.AUTH_USER_MODEL)),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signalements', to='odoo_attendance.employe')),
            ],
            options={
                'db_table': 'signalements_attendance',
                'ordering': ['-cree_le'],
            },
        ),
        migrations.AddConstraint(
            model_name='attendance',
            constraint=models.UniqueConstraint(fields=('employe', 'date'), name='unique_employe_par_jour', violation_error_code='attendance_deja_existante', violation_error_message='Cet employé a déjà une attendance enregistrée pour cette date.'),
        ),
    ]
