# Generated by Django 6.0.5 on 2026-05-18 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(max_length=20)),
                ('employee_name', models.CharField(blank=True, max_length=150, null=True)),
                ('action', models.CharField(max_length=10)),
                ('name', models.DateTimeField()),
                ('worked_hours', models.FloatField(null=True)),
                ('oodo_attendance_id', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'db_table': 'odoo_attendance',
            },
        ),
    ]
