# Generated by Django 6.0.5 on 2026-05-18 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('odoo_attendance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='oodo_attendance_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
