# Generated by Django 5.1 on 2026-07-20 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('odoo_attendance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employe',
            name='notchpay_beneficiary_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
