# Generated by Django 5.1 on 2026-06-29 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('odoo_attendance', '0002_alter_attendance_oodo_attendance_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendance',
            old_name='oodo_attendance_id',
            new_name='odoo_attendance_id',
        ),
        migrations.AddField(
            model_name='attendance',
            name='date_validation_paiement',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='statut_attendance',
            field=models.CharField(choices=[('CREATION_AUTO', 'Créé par le système'), ('CREATION_MANUELLE', "Créé par l'admin"), ('ARCHIVE', "Supprimé par l'admin")], default='CREATION_AUTO', max_length=20),
        ),
        migrations.AddField(
            model_name='attendance',
            name='statut_paiement',
            field=models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('PAYE', 'Payé'), ('IMPAYE', 'Impayé')], default='EN_ATTENTE', max_length=15),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='action',
            field=models.CharField(choices=[('sign_in', 'Entrée'), ('sign_out', 'Sortie')], max_length=10),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='worked_hours',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
