# Generated by Django 5.1 on 2026-08-28 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('odoo_attendance', '0002_employe_clientreferenceid'),
    ]

    operations = [
        migrations.AddField(
            model_name='employe',
            name='permanent',
            field=models.BooleanField(default=False),
        ),
    ]
