# Generated by Django 5.1 on 2026-07-21 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('odoo_attendance', '0002_employe_notchpay_beneficiary_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='statut_paiement',
            field=models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('PAYE', 'Payé'), ('IMPAYE', 'Impayé'), ('EN_COURS', 'En cours')], default='EN_ATTENTE', max_length=15),
        ),
    ]
