# Generated by Django 5.1 on 2026-05-16 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('odoo_id', models.CharField(max_length=20, unique=True)),
                ('nom_complet', models.CharField(max_length=150)),
                ('departement', models.CharField(max_length=100)),
                ('site_travail', models.CharField(max_length=100)),
                ('statut', models.CharField(choices=[('ACTIF', 'Actif'), ('INACTIF', 'Inactif')], default='ACTIF', max_length=10)),
                ('empreinte_template', models.BinaryField(blank=True, null=True)),
            ],
            options={
                'db_table': 'employes',
            },
        ),
    ]
