# Generated by Django 6.0.5 on 2026-05-23 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employe',
            name='statut',
            field=models.CharField(choices=[('ACTIF', 'Actif'), ('INACTIF', 'Inactif')], default='INACTIF', max_length=10),
        ),
    ]
