# Generated by Django 5.1 on 2026-06-29 15:15

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employes', '0002_alter_employe_statut'),
    ]

    operations = [
        migrations.AddField(
            model_name='employe',
            name='mobile_phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None),
        ),
    ]
