# Generated by Django 5.1 on 2026-07-20 10:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Parametre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site', models.CharField(blank=True, default='', max_length=150)),
                ('zoom', models.BooleanField(default=False)),
                ('mode', models.CharField(choices=[('SOMBRE', 'Sombre'), ('CLAIR', 'Clair')], default='CLAIR', max_length=10)),
                ('dashboard_composant_1', models.BooleanField(default=True)),
                ('dashboard_composant_2', models.BooleanField(default=True)),
                ('dashboard_composant_3', models.BooleanField(default=True)),
                ('dashboard_composant_4', models.BooleanField(default=True)),
                ('detail_composant_1', models.BooleanField(default=True)),
                ('detail_composant_2', models.BooleanField(default=True)),
                ('detail_composant_3', models.BooleanField(default=True)),
                ('detail_composant_4', models.BooleanField(default=True)),
                ('historique_composant_1', models.BooleanField(default=True)),
                ('historique_composant_2', models.BooleanField(default=True)),
                ('historique_composant_3', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='parametre', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'parametres',
            },
        ),
    ]
